import type { ApiClient, AnalyzeResponse, CreateReportRequest, CreateReportResponse, DashboardOverview, ItemResponse, Precursor, Report, ReportsListQuery, ReportsListResponse, RuleDistribution, SiteRisk, ActivityRisk } from '../types/api';

const sleep = (ms = 350) => new Promise(r => setTimeout(r, ms));
const analyses: Record<string, AnalyzeResponse> = {
  R001: { report_id: 'R001', sif_prediction: true, sif_probability: 0.91, confidence: 'High', life_saving_rules: ['Energy Isolation'], activity: 'Maintenance', location: 'Pump Area', barrier_failure: 'Isolation not verified', evidence: ['electrical isolation was not confirmed', 'technician entered the work area before isolation'], review_status: 'Pending' },
  R002: { report_id: 'R002', sif_prediction: false, sif_probability: 0.24, confidence: 'Medium', life_saving_rules: ['Line of Fire'], activity: 'Material Handling', location: 'Warehouse', barrier_failure: 'Exclusion zone not maintained', evidence: ['pedestrian crossed the marked route'], review_status: 'Reviewed' },
  R003: { report_id: 'R003', sif_prediction: true, sif_probability: 0.83, confidence: 'High', life_saving_rules: ['Working at Height'], activity: 'Inspection', location: 'Tank Farm', barrier_failure: 'Fall protection not connected', evidence: ['worker was observed at elevation without connected fall arrest'], review_status: 'Pending' },
  R004: { report_id: 'R004', sif_prediction: false, sif_probability: 0.31, confidence: 'Low', life_saving_rules: [], activity: 'Housekeeping', location: 'Workshop', barrier_failure: 'Walkway obstruction', evidence: ['loose material was present in the walkway'], review_status: 'Pending' },
  R005: { report_id: 'R005', sif_prediction: true, sif_probability: 0.76, confidence: 'Medium', life_saving_rules: ['Energy Isolation'], activity: 'Maintenance', location: 'Compressor Bay', barrier_failure: 'Isolation not verified', evidence: ['lockout verification step was skipped'], review_status: 'Pending' }
};
const reports: Report[] = [
  { id:'R001', report_text:'Technician entered the pump area before electrical isolation was confirmed.', report_type:'Near Miss', site:'Plant A', date:'2026-08-25', analysis: analyses.R001, created_at:'2026-08-25T09:12:00Z' },
  { id:'R002', report_text:'Pedestrian crossed a material handling route while a load was being moved.', report_type:'UA', site:'Plant B', date:'2026-08-24', analysis: analyses.R002, created_at:'2026-08-24T11:20:00Z' },
  { id:'R003', report_text:'Inspector was working at elevation without connecting the fall arrest system.', report_type:'Near Miss', site:'Plant A', date:'2026-08-23', analysis: analyses.R003, created_at:'2026-08-23T08:42:00Z' },
  { id:'R004', report_text:'Loose material was found in a workshop walkway.', report_type:'UC', site:'Plant C', date:'2026-08-22', analysis: analyses.R004, created_at:'2026-08-22T13:05:00Z' },
  { id:'R005', report_text:'Maintenance work started before lockout verification was completed.', report_type:'Incident', site:'Plant B', date:'2026-08-21', analysis: analyses.R005, created_at:'2026-08-21T15:31:00Z' }
];
const overview: DashboardOverview = { total_reports: 10284, sif_reports: 2341, sif_percentage: 22.76, critical_precursors: 47 };
const sites: ItemResponse<SiteRisk> = { items: [{site:'Plant A',report_count:1000,sif_count:120,sif_density:0.12},{site:'Plant B',report_count:820,sif_count:164,sif_density:0.20},{site:'Plant C',report_count:610,sif_count:61,sif_density:0.10}] };
const activities: ItemResponse<ActivityRisk> = { items: [{activity:'Maintenance',report_count:1000,sif_count:300,sif_density:0.30},{activity:'Material Handling',report_count:700,sif_count:105,sif_density:0.15},{activity:'Inspection',report_count:520,sif_count:62,sif_density:0.119}] };
const rules: ItemResponse<RuleDistribution> = { items: [{rule:'Energy Isolation',count:380,percentage:38},{rule:'Working at Height',count:250,percentage:25},{rule:'Line of Fire',count:180,percentage:18},{rule:'Vehicle Safety',count:120,percentage:12}] };
const precursors: ItemResponse<Precursor> = { items: [{id:'P001',activity:'Maintenance',location:'Plant A',barrier_failure:'Isolation not verified',occurrence_count:37,sif_count:21,sif_density:0.568,trend_percentage:18,affected_sites:['Plant A','Plant B']},{id:'P002',activity:'Inspection',location:'Tank Farm',barrier_failure:'Fall protection not connected',occurrence_count:22,sif_count:11,sif_density:0.5,trend_percentage:9,affected_sites:['Plant A']},{id:'P003',activity:'Material Handling',location:'Warehouse',barrier_failure:'Exclusion zone not maintained',occurrence_count:31,sif_count:7,sif_density:0.226,trend_percentage:-4,affected_sites:['Plant B','Plant C']}] };

export class MockApi implements ApiClient {
  async createReport(payload: CreateReportRequest): Promise<CreateReportResponse> { await sleep(); const id=`R${String(reports.length+1).padStart(3,'0')}`; return { id, report_text:payload.report_text, report_type:payload.report_type, site:payload.site, date:payload.date, created_at:new Date().toISOString() }; }
  async analyzeReport(id: string): Promise<AnalyzeResponse> { await sleep(1000); const existing=analyses[id] || { report_id:id,sif_prediction:false,sif_probability:0.18,confidence:'Low',life_saving_rules:[],activity:'Not available',location:'Not available',barrier_failure:'Not available',evidence:['Mock analysis result — replace with backend output.'],review_status:'Pending' }; return existing; }
  async getReport(id: string): Promise<Report> { await sleep(); const r=reports.find(x=>x.id===id); if(!r) throw new Error('Report not found'); return r; }
  async listReports(query: ReportsListQuery = {}): Promise<ReportsListResponse> { await sleep(450); let items=[...reports]; if(query.search) { const q=query.search.toLowerCase(); items=items.filter(r=>`${r.report_text} ${r.site||''} ${r.analysis?.activity||''}`.toLowerCase().includes(q)); } if(query.sif==='sif') items=items.filter(r=>r.analysis?.sif_prediction); if(query.sif==='non-sif') items=items.filter(r=>r.analysis && !r.analysis.sif_prediction); if(query.site) items=items.filter(r=>r.site===query.site); if(query.activity) items=items.filter(r=>r.analysis?.activity===query.activity); if(query.rule) { const rule=query.rule; items=items.filter(r=>r.analysis?.life_saving_rules.includes(rule)); } const page=query.page||1, pageSize=query.pageSize||5; return {items:items.slice((page-1)*pageSize,page*pageSize),total:items.length,page,page_size:pageSize}; }
  async getDashboardOverview(){await sleep();return overview;} async getDashboardSites(){await sleep();return sites;} async getDashboardActivities(){await sleep();return activities;} async getDashboardRules(){await sleep();return rules;} async getDashboardPrecursors(){await sleep();return precursors;}
}
